grpc/proposal

A6-client-retries.md
Correct me if I'm wrong, but my understanding is that `token_count` should be incremented only if it's lower than `maxTokens`. Otherwise it'll grow indefinitely so if service will be stable for a day and generate 1M tokens, next day 1h outage won't trigger the algorithm.
cc @ericgribkoff @ncteisen @ejona86
=> Clarify retry budgeting algorithm

G1-true-binary-metadata.md
Please direct discussion here: https://groups.google.com/forum/#!topic/grpc-io/Ww8waYz_Nes
=> G1: Add proposal for true binary metadata

A6-client-retries.md
Clarification of transparent retries stemming from an offline discussion.
=> Clarify Transparent Retries

A2-service-configs-in-dns.md
Also a couple of other updates:
- Fix quote character used in JSON.
- Update information on C-core implementation.
=> A2 update: Specify "_grpc_config." prefix for DNS name.

A2-service-configs-in-dns.md
The restrictions here do not affect that of the service config object contained in the choice.
=> clarify service config in DNS

L17-c++-sync-server-exceptions.md
Relates to grpc/grpc#13706 and grpc/grpc#13815.
Please discuss in https://groups.google.com/forum/#!topic/grpc-io/u1XmQPAi3fA
Even though the implementation is quite simple and localized in scope, I feel that it needs a gRFC and discussion because this amounts to a permanent promise that the sync server will catch exceptions from method handlers.
Cc: @yang-g @ctiller @dgquintas
=> L17: C++ synchronous server should catch exceptions from method handlers

P3-grfcs-for-core-api-changes.md
As wrapped languages move to their own repositories and more community language bindings emerge, it is increasingly important to stabilize core surface APIs and treat them as a promise for the future rather than just an implementation mechanism.
=> P3: Core API changes (including additions) need a gRFC

A3-channel-tracing.md
This is needed for the .proto to actually compile.
Realized while working on grpc/grpc#13883
=> Update ChannelTraceEvent::Severity enum

L23-node-protobufjs-library.md
This was in the original proposal, but it was removed. Now I think it should be added again because a synchronous loader function is useful when a user needs to re-export objects derived from the loaded service information.
=> L23 edit: add a synchronous proto loader function

A14-channelz.md
The other members all have `_ref` suffixes.
=> A14-channelz: rename field to socket_ref for consistency

A14-channelz.md
The previous PR updated Channel but failed to update Subchannel.
=> A14-channelz: rename to socket_ref for consistency in Subchannel

A6-client-retries.md
The number of transparent retries tracked by this metadata key can be at most 1, so it has minimal value on the server-side. 
cc @dapengzhang0
=> Remove grpc-transparent-retry-attempts metadata

A14-channelz.md
The standard ciphersuite name already includes both the key exchange and the cipher. The naming convention is: `TLS_<key_exchange>_WITH_<cipher>_<hash>`:
https://tools.ietf.org/html/rfc4346#appendix-C
Just exposing the RFC name lets us avoid string parsing in every channelz implementation. It also exposes the hash algorithm for free.
I confirmed the Java SSL API provides an easy way to get this standard name. 
For C, there is https://www.openssl.org/docs/manmaster/man3/SSL_CIPHER_get_name.html:
> SSL_CIPHER_standard_name() returns a pointer to the standard RFC name of cipher. If the cipher is NULL, it returns "(NONE)". If the cipher has no standard name, it returns NULL. If cipher was defined in both SSLv3 and TLS, it returns the TLS name.
For Go: …
=> Update A14-channelz.md to use RFC ciphersuite names

A1-http-connect-proxy-support.md, A8-client-side-keepalive.md, A9-server-side-conn-mgt.md
@MakMukhi, @vjpai, could you help get similar changes in place for A8 and A9? Note that C probably needs to explicitly state the mapping from each spec-defined option; I sort of expect it wouldn't be obvious just given the option names.
CC @markdroth, @zpencer
=> Reference Java APIs for implemented proposals

A6-client-retries.md
JSON numbers (used by Proto's JSON format for the Duration type) must have a digit before the decimal place, so ".1s" was failing to parse.
Thanks for catching this @dapengzhang0
=> Fix error in the JSON representation of a proto Duration

L23-node-protobufjs-library.md
Changing the `include` option name to `includeDirs` based on feedback from an internal API review.
=> Change include option name in Node Protobuf.js library

L12-csharp-interceptors.md
Addresses https://github.com/grpc/grpc/issues/11646
Implementation: https://github.com/grpc/grpc/pull/12613
Discussion: https://groups.google.com/d/topic/grpc-io/GKcnFC3oxhk/discussion
=> L12: C# Interceptors Proposal

L29-opencensus-filter.md
This will add a new public API call to register the OpenCensus filter for tracing and stats collection.
=> L29: gRPC C++ API Changes for OpenCensus Integration

A6-client-retries.md
The maximum value for `maxTokens` is obviously open for debate.  This was just a value I chose randomly that seemed like more than most people would want to use.
=> A6-client-retries: minor clarifications and define a maximum value for maxTokens

A3-channel-tracing.md
@markdroth, @carl-mastrangelo, @dapengzhang0, @lyuxuan, feel free to chime in if you think this list should be longer or shorter or modified in any way
=> Add Minimal Set of Channel Trace Events

A17-client-side-health-checking.md
=> A17: Client-Side Health Checking

L39-remove-grpc-use-signal.md
This core surface API is no longer useful and doesn't seem to be used.
=> L39: Remove grpc_use_signal from core surface API

L41-node-server-async-bind.md
Discussion thread: https://groups.google.com/forum/#!topic/grpc-io/Uio1Ja6GRHI
=> L41: Asynchronous port binding method in Node Server API

A10-avoid-grpclb-and-service-config-for-localhost-and-ip-literals.md
When a grpc client that <i>doesn't</i> support grpclb-in-DNS or service configs connects to "localhost", is can resolve "localhost" is negligible time with a quick "hosts" file lookup. But clients that do support these must also query for TXT and SRV records (of `_grpclb._tcp.localhost` and `_grpc_config.localhost`), and these queries must go over the  network and (presumably in the common case) come back with NXDOMAIN. (from what I've observed) it's not uncommon for these "TXT/SRV lookup -> NXDOMAIN" RTT's to be on the order of 10's or 100's of milliseconds, and can potentially add an order of magnitude increase to channel setup latency when resolving "localhost". This gRFC discusses this issue, and the solution described here potentially affects all languages. 
Updated with grpc-io …
=> A10: Don't support grpclb-in-DNS and service-config for "localhost" and ip literals

L42-metadata-flags.md, L42-python-metadata-flags.md
Please view the gRFC at https://github.com/lidizheng/proposal/blob/master/L42-python-metadata-flags.md
PR: https://github.com/grpc/grpc/pull/16919
Issue: https://github.com/grpc/grpc/issues/6770
=> L42 Surface 'wait-for-ready' setting in Python client

A24-lb-policy-config.md
@AspirinSJL pointed out that I missed this in grpc/grpc#17693.
I had originally intended all instances of this field to be repeated, but I somehow didn't get it right in the gRFC (or in our internal proto definition, which I'll fix if we agree on this change).  I think the rationale for this is the same in all cases: we want the ability to select an LB policy that may not be known to all clients.
Any objections?
=> Use repeated for all instances of LoadBalancingConfig message.

A24-lb-policy-config.md
Recent change (#120) made the childPolicy and fallbackPolicy fields to be repeated. Thus the corresponding json string should have square brackets to indicate JSON array.
=> Update example json string in LB Policy Config

L44-python-rich-status.md
gRFC: https://github.com/lidizheng/proposal/blob/python-rich-status/L44-python-rich-status.md
Discussion Thread: https://groups.google.com/forum/#!topic/grpc-io/8Ys6ba8gpLc
=> L44: New RPC Status API for Python

A6-client-retries.md
As per #100, we want to explicitly specify the validation rules for each field in the service config.
=> A6 update: Explicitly specify validation rules for retryPolicy, hedgingPolicy and retryThrottling

A21-Service-Config-Error-Handling.md
Discussion thread at https://groups.google.com/forum/#!topic/grpc-io/bAxyse6c2eI
=> A21-Service-Config-Error-Handling

L23-node-protobufjs-library.md
This is a followup to https://github.com/grpc/grpc-node/issues/805 and a request to officially allow `load` and `loadSync` methods of `@grpc/proto-loader` accept multiple files.
Rationale:
- The cost of this change is nearly zero, since Protobuf.js `Root.load` [supports](https://github.com/protobufjs/protobuf.js/blob/c72c752352347555406bafd7121acaed240fbf23/src/root.js#L190-L191) this use case. It's just a TypeScript type change.
- We in Google Cloud API Client Tools often need to load several `.proto` files for one client ([example](https://github.com/googleapis/nodejs-pubsub/blob/c72491f9c3e68fff5d05f13ae73ea7e75b90c18b/src/v1/subscriber_client.js#L93-L103)) so we need to call `load` individually for each `.proto` file and then use `lodash.merge` to merge them (`Object.assign` is not …
=> make load, loadSync accept multiple files at once

A21-service-config-error-handling.md
Add note about receiving NO SERVICE CONFIG.
This differentiates the NO SERVICE CONFIG case from the valid service config or invalid service config cases.
=> Add note about receiving NO SERVICE CONFIG

L59-core-allow-cppstdlib.md
This is a proposal to allow C++ standard library in gRPC Core Library and gRPC Core will be full C++11  compliant with this.
[Discussion Thread](https://groups.google.com/forum/#!topic/grpc-io/umQyyXmNr2w)
=> L59 - Allow C++ standard library in gRPC Core Library

L60-core-remove-custom-allocator.md
I'll add a link to the discussion once initial review is done.
=> L60: Remove custom allocation function overrides from core surface API

A26-grpclb-selection.md
Modify the method for enabling gRPCLB to not require any special handling in core, allowing for stabilization of the gRPCLB protocol and load balancing policy.
@ejona86 @markdroth - Please also provide implementation steps for C/Java if appropriate.  Thanks!
=> A26: gRPCLB Selection

L61-core-call-credential-security-level.md, L62-core-call-credential-security-level.md
Associate a transport security level to each call credential and channel and allow the call credential to be transferred over a channel if and only if the security level of a channel is greater than or equal to that of call credential.
=> gRFC L62-core:gRPC security level negotiation between channels and call creds

L65-python-package-name.md
> gRPC Python is uploaded as `grpcio` on PyPI, but there is another package named
`grpc`. Hence some users are confused. This document proposes gRPC Python to
upload additional packages named `grpc` and `grpc-*` as proxies to our official
packages.
=> L65: Additional PyPI Packages for gRPC Python

L66-core-cancellation-status.md
This is a breaking API change at core but not at the wrapped languages.
This is implemented in grpc/grpc#22991
=> L66: Core server RPCs will not report cancellation if completed with non-OK status

A27-xds-global-load-balancing.md
This came up in discussion in #170, but it didn't make it into the text of the gRFC.  Adding it now for future reference.
=> Add note to A27 about not supporting endpoint-level weights.

A21-service-config-error-handling.md
As we've discussed, this is necessary to support the new ConfigSelector API (the details of which will be described in Doug's forthcoming gRFC about the RouteAction design).
=> A21 update: Do not use default service config on transient resolver failure

L74-java-channel-creds.md
Take special note of how ManagedChannelBuilders are created.
=> L74: Java Channel Credentials

L77-core-cpp-third-party-identity-support-for-call-credentials.md
This proposal is a continuation of the open PR:
https://github.com/grpc/proposal/pull/215
=> L77: Core and C++ Third Party Identity Support for Call Credentials

A33-Fault-Injection.md
gRFC: https://github.com/lidizheng/proposal/blob/fault-injection/A33-Fault-Injection.md
=> A33: Client-Side Fault Injection

A36-xds-for-servers.md
See "open issues" at the end of the doc. At the time of creation, Go and C are much more tentative than Java.
CC @sanjaypujare, @dfawley, @markdroth
=> A36: xDS-Enabled Servers

A33-Fault-Injection.md
Add details about how to handle aborting with 200/OK status code, and several header corner cases.
=> Patch the gRFC A33 with details around 200/OK and headers

A40-csds-support.md
gRFC: https://github.com/lidizheng/proposal/blob/csds/A40-csds-support.md
=> A40 - xDS Configuration Dump via Client Status Discovery Service in gRPC

A38-admin-interface-api.md
gRFC: https://github.com/lidizheng/proposal/blob/admin-interface/A38-admin-interface-api.md
This proposal describes a convenience API in each gRPC language to improve the usability of creating a gRPC server with admin services.
=> A38: Admin Interface API

A36-xds-for-servers.md
The previous behavior was undefined. We don't know why someone would
need the host:port included multiple times, but there's not much point
in stopping them.
CC @easwars, @yashykt, @sanjaypujare, @dfawley
=> A36: If multiple %s in template, replace them all

A36-xds-for-servers.md
If no HTTP filters are implemented, it'd require plumbing
interceptors/filters _just_ for failing RPCs if Router is missing.
That places unnecessary burden on implementations for relatively small
benefit. We want the behavior, but it is only required when
implementations will already have the plumbing available to implement it
trivially.
CC @easwars, @yashykt, @sanjaypujare, @dfawley
=> A36: Allow missing Router in http_filters for L4-only servers

A36-xds-for-servers.md
This behavior is all implicitly defined by Envoy, so is just documenting
the behavior instead of deciding what the behavior should be.
CC @easwars, @yashykt, @sanjaypujare, @dfawley
=> A36: Explicitly define duplicate matcher behavior

L74-java-channel-creds.md
All the class definitions were swapped from exposing constructors to
factory methods, but the examples weren't.
=> L74: Fix missed updates to factory methods

L80-cpp-async-response-reader-destruction.md
See previous discussion in https://github.com/grpc/grpc/pull/26233.
@ctiller I've set you as the approver after the discussion in the thread above. Feel free to re-assign if that's not appropriate. Thanks!
=> L80: Add a proposal for ClientAsyncResponseReaderInterface destruction.

L73-java-binderchannel.md
By considering the binding Intent's action, data, type, identity and categories we align BinderChannel's addressing with Android's natural equivalence relation for "cached" IBinders (https://developer.android.com/guide/components/bound-services#Basics)
=> Update the AndroidComponentAddress spec to include the whole binding Intent

A36-xds-for-servers.md
Since destination_ports is not an array (a singleton) and source_prefix_ranges is an array.
=> A36: replace destination_ports with source_prefix_ranges in the example

A36-xds-for-servers.md
This is to match Envoy's handling. See also
https://github.com/grpc/proposal/pull/250 for the http filter change.
=> A36 update: Require HCM to be the terminal network filter

A39-xds-http-filters.md
This matches Envoy's handling, removes special-case handling that we had for the router filter, and allows us to catch more problems at config validation time.
C-core implementation in grpc/grpc#26742.
=> A39 update: Add support for terminal filters.

A29-xds-tls-security.md, L80-cpp-async-response-reader-destruction.md
CC @ejona86 @dfawley @yashykt @easwars pls review.
=> A29: xDS-Based Security for gRPC Clients and Servers

A28-xds-traffic-splitting-and-routing.md, A36-xds-for-servers.md
The text permitted certain carve-outs if RouteConfiguration was not
being observed, but it didn't describe the behavior if
RouteConfiguration _was_ observed.
-----
Split out of #237, as it is grown a bit.
CC @markdroth, @dfawley, @yashykt, @YifeiZhuang, @zasweq
=> A36 update: Document expected behavior when observing RouteConfiguration

L81-cpp-call-failed-before-recv-message.md, L84-cpp-call-failed-before-recv-message.md
Proposal to move `grpc_call_failed_before_recv_message` from subsurface to the C-core surface API.
=> L84: Add grpc_call_failed_before_recv_message() to C-core API

L73-java-binderchannel/wireformat.md
The flow control mechanism is specified in the internal document but was not included in this proposal. Also, both documents didn't contain the description of the flag `FLAG_MESSAGE_DATA_IS_PARTIAL`, which is crucial when breaking larger message into smaller chunks for flow control purposes.
This PR copies the description of flow control mechanism in the internal document to the proposal, and explicitly introduce `FLAG_MESSAGE_DATA_IS_PARTIAL` and its usage. Additionally, the `num bytes` field in `ACKNOWLEDGE_BYTES` requests should be of type `long` (64 bits) instead of `int` (32 bits) judging from the implenmentation.
=> Specify the flow control behavior in BinderChannel protocol

G2-http3-protocol.md
A specification for gRPC over HTTP/3.
There is a lot of overlap with the content in https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md. For example, request and response headers are unchanged between HTTP/2 and HTTP/3. Rather than duplicate content, the proposal focuses on the differences between HTTP/2 and HTTP/3.
Preview: https://github.com/JamesNK/proposal/blob/jamesnk/http3/G2-http3-protocol.md
=> G2: gRPC over HTTP/3

L92-dotnet-grpc-web.md
Proposal for adding gRPC-Web support to grpc-dotnet using an in-process proxy and a gRPC-Web client.
@jtattermusch 
Preview URL: https://github.com/JamesNK/proposal/blob/jamesnk/dotnet-grpc-web/L92-dotnet-grpc-web.md
=> L92: grpc-dotnet gRPC-Web proposal

A50-xds-outlier-detection.md
That name refers to a field in the `OutlierDetection` xDS proto message, so this fix makes it use the proper field name.
=> A50: Fix a find/replace error

A52-xds-custom-lb-policies.md
Mention that udpa.type.v1.TypedStruct should also be considered when looking for a custom LB configuration.
@markdroth
=> xds: UDPA TypedStruct custom LB config support

A41-xds-rbac.md
The proper behavior is subtle and easy to assume incorrectly. This
caused a bug in Go (https://github.com/grpc/grpc-go/issues/4896) and
would be easy for other implementations to assume incorrectly.
As determined by Envoy's behavior:
https://github.com/envoyproxy/envoy/blob/7d3e444d757696c15a4020b1d2d8ba5cb7f12501/source/common/http/header_utility.cc#L140-L146
CC @YifeiZhuang, @zasweq, @ashithasantosh, @yashykt 
----
This got brought up recently in https://github.com/grpc/grpc/pull/27754, where it was pointed out MetadataMatcher.invert behaves differently. MetadataMatcher.invert was added after this gRFC, so I'm not yet calling out its behavior. But I did see that Go's behavior didn't match the necessary behavior, so let's at least take a baby step and define the behavior of …
=> A41 update: Call out precise HeaderMatcher.invert_match semantics

A50-xds-outlier-detection.md
As discussed out of band, the state should be reset more fully when disabling the timer when the OD LB policy is provided a config that completely disables ejection.
=> A50 update: Improve handling of disabling the timer

A50-xds-outlier-detection.md
The previous text here was an incorrect interpretation/transcription of the Envoy spec. [The relevant part of the Envoy spec](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/upstream/outlier#failure-percentage) says
> Detection also will not be performed for a cluster if the number of hosts with the minimum required request volume in an interval is less than the [outlier_detection.failure_percentage_minimum_hosts](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/cluster/v3/outlier_detection.proto#envoy-v3-api-field-config-cluster-v3-outlierdetection-failure-percentage-minimum-hosts) value.
=> A50 update: Fix failure percentage minimum hosts check

A50-xds-outlier-detection.md
The Envoy spec is ambiguous on the behavior when the values are equal. The implementation code, e.g. [here](https://github.com/envoyproxy/envoy/blob/main/source/common/upstream/outlier_detection_impl.cc#L465) continues with ejection if the current ejection percent is strictly less than the configured max percent, so to match that behavior we should stop if the current ejection percent is greater than or equal to the configured maximum.
=> A50 update: Switch behavior when ejection percentage is equal to max

A42-xds-ring-hash-lb-policy.md
Compliments some changes that have been made or are being made:
- https://github.com/grpc/grpc-java/pull/9453
- https://github.com/grpc/grpc-go/pull/5591
- https://github.com/grpc/grpc/pull/28986
=> A42 update: io.grpc.channel_id should be initialized with a random number

L70-node-proto-loader-type-generator.md
Update `proto-loader-gen-types` proposal to match PR: https://github.com/grpc/grpc-node/pull/2183
=> L70 update: Message name templates for proto-loader-gen-types

A30-xds-v3.md
The xDS ecosystem no longer plans to release a new version of the xDS API every year.  As a result, we no longer need a policy of supporting two versions of xDS at any given time, so I am removing that content from this gRFC.
gRPC plans to drop support for xDS v2 in the near future.
=> A30 update: remove info about ongoing xDS version changes

A6-client-retries.md
This PR includes a few different changes that we discussed while I was implementing the feature in Node. The main changes are:
- Removing the underspecified statement that LB policies should use a list of previous backend choices when choosing a new backend.
- Making the specifics of the memory management configuration options implementation choices.
- Clarifying how LB policy pick results should be handled by retry logic, and how the client library detects that "The RPC reaches the server, but has never been seen by the server application logic".
- Making it optional for client libraries to expose the `grpc-previous-rpc-attempts` value in response metadata.
I also wanted to update the graphics for the Transparent Retries section, but I don't know where the original drawings are.
=> A6 update: make changes based on conversations

A37-xds-aggregate-and-logical-dns-clusters.md
The specific changes are as follows:
- Describe where the newly used data is in the `Cluster` proto message
- Describe how errors from CDS and EDS watchers and DNS resolves should be handled
- Describe the validation rules for the newly used data in the `Cluster` proto message
- A couple of other notes from the conversation
=> A37 update: add missing details

A47-xds-federation.md
To make sure you don't have the same bug we had in C-core and Java when you implement this in Node. :)
=> A47 update: specify where where env var guard needs to be checked

A47-xds-federation.md
Use the correct default value of the `client_listener_resource_name_template` field.
=> A47 update: Fix a typo in the Multiple Authorities example

A42-xds-ring-hash-lb-policy.md
For context, see discussion in https://github.com/grpc/grpc/pull/32326.
=> A42 update: picker must contain its own copy of the subchannel connectivity states

P4-grpc-cve-process.md
The grpc/grpc repo split their template into one-per-language, so there's not a single clear link to replace it with. Replace the mention of the template with a reminder that we need to know what language is impacted. But otherwise it seems the only practical thing is to trust they will send detailed enough information or respond when we ask for additional details.
=> P4 update: Remove dead link to ISSUE_TEMPLATE

A65-xds-mtls-creds-in-bootstrap.md
Addresses https://github.com/grpc/grpc/issues/32977.
=> A65: mTLS Credentials in xDS Bootstrap File

A47-xds-federation.md
As suggested by @murgatroid99.
=> A47 update: EDS resource name field is required for new-style CDS resources

A48-xds-least-request-lb-policy.md
Per [proto validation rules](https://github.com/grpc/grpc-java/blob/40bff673c0422d88bc6b7cf99281afefa026a01e/xds/third_party/envoy/src/main/proto/envoy/extensions/load_balancing_policies/least_request/v3/least_request.proto#L28) and gRPC-Java source code inspection.
=> A48 Update: clarify choice_count < 2 behavior

A42-xds-ring-hash-lb-policy.md
This clarifies a few points that I found confusing:
- How hashes from multiple hash policies should be combined
- How the `terminal` bit should be handled
- What number "8M" refers to
- How the ring should be constructed
=> A42 update: Clarify a few points in the design

L105-python-expose-new-error-types.md
Add two new errors in grpc public API.
Discussion thread: https://groups.google.com/g/grpc-io/c/pG34X9nAa3c
=> L105: Python Add New Error Types

A58-audit-logging.md, A59-audit-logging.md
Still lacking the language-specific API sections. But I'd like to open this up so that folks commenting on https://github.com/envoyproxy/envoy/pull/26001 can have more context.
=> A59: gRPC Audit Logging

A48-xds-least-request-lb-policy.md
Implementing this using the Go "base" balancer package turned out to be more trouble than it was worth, most likely.
=> Update A48: remove reference to Go's base balancer

L108-node-grpc-reflection-library.md
adding proposal as discussed in grpc/grpc-node#79
=> L108: Node.js Reflection Server Library

A51-custom-backend-metrics.md
The previously linked version was missing key fields, which are necessary for A58 to make sense.
=> A58 update: Update link to LoadReport proto

A66-otel-stats.md
This PR adds target and method label value filtration as part of the knobs provided to users for the grpc-go Open Telemetry component.
=> Update Go OTel API

A47-xds-federation.md
We decided on this behavior a while ago, but it looks like we forgot to update the gRFC.
=> A47 update: fix spec for data plane authority

L117-core-replace-gpr-logging-with-abseil-logging.md
L117: C-core: replace gpr logging with absl logging.
Marking as final.
=> L117: C-core: replace gpr logging with absl logging. Marking as final.

A78-grpc-metrics-wrr-pf-xds.md
The previous description explains how histograms work which seems unnecessary.
=> A78 Update: WRR: Fix description of metric

L117-core-replace-gpr-logging-with-abseil-logging.md
- Remove stack trace flag.
- Updating the pseudo code to include the SetVLogLevel calls.
- https://github.com/grpc/grpc/blob/master/src/core/util/log.cc
=> L117 update: Remove stack trace flag

A6-client-retries.md
See discussion in https://github.com/grpc/grpc-go/issues/7514.
=> A6 update: change specification of backoff behavior to make sense

A72-open-telemetry-tracing.md
Changes - 
* Add link to OpenCensus's binary format for grpc-trace-bin
* Add names for parent call span, attempt span and server span based on existing OpenCensus implementation.
* Clarify `previous-rpc-attempts` does not include transparent retries as per https://github.com/grpc/proposal/blob/master/A45-retry-stats.md
* Add missing `sequence-number` attribute from events in examples.
* Remove superfluous and confusing `sent` and `received` words from `Inbound message received` and `Outbound message sent`. Reasoning - `Inbound` and `Outbound` already convey the direction. The way it is currently structured, you could have `Outbound message sent` followed by `Outbound message compressed` , and `Inbound compressed message` followed by `Inbound message received`. In the future, we might want …
=> A72 update: various clarifications and corrections

A42-xds-ring-hash-lb-policy.md, A61-IPv4-IPv6-dualstack-backends.md
Fix logic for ring_hash proactive connection attempts to trigger even if the state update was not triggered by an endpoint entering TRANSIENT_FAILURE state.  This addresses two edge cases spotted by @arjan-bal:
1. There are four endpoints in the following states: TF, TF, READY, and IDLE. If the READY endpoint fails, it transitions to IDLE, resulting in the new states: TF, TF, IDLE, IDLE.
2. There are four endpoints in the following states: TF, TF, CONNECTING, and IDLE. If the CONNECTING endpoint is removed, the new states become: TF, TF, IDLE.
=> A61 update: fix ring_hash proactive connection attempt logic

L35-node-getAuthContext.md
This is one way to implement the change proposed in https://github.com/grpc/grpc-node/issues/2730. #440 was an alternative option to do that, but I disagreed with the specific changes there and progress stalled on that proposal.
Now doing this will be useful for implementing RBAC ([gRFC A41](https://github.com/grpc/proposal/blob/master/A41-xds-rbac.md)).
=> L35 update: expand getAuthContext return contents in grpc-js

A74-xds-config-tears.md
The original intent here was that the xds resolver would handle `OnError()` the same way that it did prior to A74: it would return a result to the channel that had an error for the service config, which would cause the channel to ignore the update if it had already previously seen a valid result.  This poses a problem for cases like receiving a socket listener instead of an API listener or receiving a route config that does not contain a virtual host matching the channel's default authority, because in those cases we want to stop using the previously seen resources and start failing data plane RPCs.
This change fixes that by specifying that the xds resolver will see errors only in cases where we want to stop using the previously received resources, if any.  As a result, we are able to …
=> A74 update: improve XdsDependencyManager watcher API

L112-node-server-interceptors.md
RBAC needs to be able to examine the addresses of the two endpoints used to make a request, and `getConnectionInfo` covers that. The `getAuthContext` method is defined in gRFC L35, and this just explicitly states that it is on the `ServerInterceptingCall`.
=> L112 update: Add `getConnectionInfo` and `getAuthContext` to `ServerInterceptingCall`

A78-grpc-metrics-wrr-pf-xds.md, A94-subchannel-otel-metrics.md
Closes https://github.com/grpc/grpc/issues/34886
=> A94: OTel metrics for Subchannels
