L1-c++-stream-coalescing.md, L1.md
Discussion at: https://groups.google.com/forum/#!topic/grpc-io/GfxB7nuV9GY
This is re-opening/re-creating #2 since GitHub seems to have lost the link between my fork and this repository.
=> Initial draft of stream coalescing for C++

L6-allow-c++-in-grpc-core.md
Please discuss at https://groups.google.com/forum/#!topic/grpc-io/yAg-ydC77aE.
=> L6: Proposal to allow C++ in gRPC core library

L11-Ruby-Interceptors.md
FYI @mehrdada @apolcyn 
See https://github.com/grpc/grpc/pull/12100 for more information.
gRPC.io Google Group discussion: https://groups.google.com/d/msg/grpc-io/YRfZe7IH69k/FdSI_CGEAAAJ
=> L11: Add Ruby Client and Server Interceptors

A6-client-retries.md
=> Clarify maxRetryAttempts

A8-client-side-keepalive.md
grpc-io discussion: https://groups.google.com/d/topic/grpc-io/Yc5_vSUJgwQ/discussion
=> A8: Client-side keepalive

A9-server-side-conn-mgt.md
grpc-io discussion: https://groups.google.com/d/topic/grpc-io/DIiIMiq9sV8/discussion
=> A9: Server-side connection management

A6-client-retries.md
Changes durations from millisecond number values, to well defined strings of the form "1.23s".
cc @carl-mastrangelo 
Also addresses two smaller clarifications of grpc-retry-attemps and grpc-retry-pushback-ms
=> Updates to Retry Spec

L18-remove-grpc-alarm.md
Implemented in grpc/grpc#14015
=> L18: Remove alarm from core and re-implement C++ version

L15-PHP-Interceptors.md
Implementation: https://github.com/grpc/grpc/pull/13342
=> L15-PHP-Interceptors

L23-node-protobufjs-library.md
Discussion thread: https://groups.google.com/forum/#!topic/grpc-io/t7XFE7Wevow
=> L23 - Standalone Node.js gRPC+Protobuf.js Library API

A14-channelz.md
Fix some garbed text and a renamed message, so that the proto compiles.
=> A14: make channelz proto compilable

A14-channelz.md, A3-channel-tracing.md
Removes `status` and `state`, adds `is_error_condition`
=> Update Channel Tracing Proto

A9-server-side-conn-mgt.md
There should not be any _required_ change to the code based on this. I use the word "ideally" to say "go probably want to do it this way" but "it's not the worst thing to do something differently." If you are doing something differently though, it may be good to discuss what and why, to make sure edge cases are covered.
CC @MakMukhi, @vjpai, @yashykt
=> A9: Clarify MAX_CONNECTION_AGE_GRACE

A8-client-side-keepalive.md, A9-server-side-conn-mgt.md
@yashykt, please verify that the mapping is correct.
=> keepalive: Document C's option names

L32-node-channel-API.md
Discussion thread: https://groups.google.com/forum/#!topic/grpc-io/VR0C7DiG7bs
=> L32: Add a public Channel API to the Node library

L33-node-checkServerIdentity-callback.md
Discussion thread: https://groups.google.com/forum/#!topic/grpc-io/ucorPSDGIIo
=> L33 Create proposal for checkServerIdentity callback in Node.

A6-client-retries.md
=> Update Implementation Status of Retries

L40-node-call-invocation-transformer.md
Discussion thread: https://groups.google.com/forum/#!topic/grpc-io/f3v4SBvj7L4
=> L40: Node Call Invocation Transformer API

L31-php-intercetor-api-change.md
Since we haven't release the PHP interceptor, I think this is a good time for us to update before the first release.
=> L31: PHP interceptor API Change with Deserialize Argument

A14-channelz.md
cc @lyuxuan @menghanl @zpencer
=> Channelz: Add GetServer Method

A24-lb-policy-config.md
Add validation rules as per #100
=> A24 update: Add validation rules as per #100

A17-client-side-health-checking.md
Specify validation rule as per #100
=> A17 update: Specify validation rule as per #100

A2-service-configs-in-dns.md
Update after A21 service config error handling changes
=> Update after A21 service config error handling changes

A21-service-config-error-handling.md
Clarifying that this is for service config obtained from a resolver. Otherwise, what does a "resolved" service config mean?
=> Fix "resolved service config"

L49-objc-flow-control.md
Discussion link: https://groups.google.com/forum/#!topic/grpc-io/xSOtIAKSESk
=> L49: Objective-C Flow Control

P4-grpc-cve-process.md
Proposal to define the CVE process for gRPC
=> P4: Proposal for gRPC's CVE process.

L51-java-rm-nano-proto.md
Discussion thread: https://groups.google.com/d/topic/grpc-io/ErFnaXbIuZc/discussion
Implementation: https://github.com/grpc/grpc-java/pull/5622
=> L51: Java Remove Nano Protobuf

A6-client-retries.md
See discussion thread https://github.com/grpc/grpc-java/pull/5827#discussion_r294972157 for details.
=> Allow empty nonfatalStatusCodes in hedging policy

L54-python-server-wait.md
gRFC: https://github.com/lidizheng/proposal/blob/python-wait/L54-python-server-wait.md
Group Thread: https://groups.google.com/forum/#!topic/grpc-io/GhJl_JHfaHA
=> L54: Python Server Wait API

L52-core-static-method-host.md
This proposal requires a major version bump.
=> gRFC for static method and host.

CODE-OF-CONDUCT.md, GOVERNANCE.md, README.md
Add CODE-OF-CONDUCT.md, GOVERNANCE.md and update README.md
=> Add CODE-OF-CONDUCT.md, GOVERNANCE.md and update README.md

P4-grpc-cve-process.md
=> change status to approved

A27-xds-global-load-balancing.md
As per internal discussion, the wording here was too strict.
=> A27 update: localities may contain 0 endpoints

L64-python-runtime-proto-parsing.md
Update runtime proto parsing status to "Implemented".
=> Update L64 Runtime Proto Parsing to implemented

A31-xds-timeout-support-and-config-selector.md
Ref: https://github.com/envoyproxy/envoy/pull/13247
=> A31: update xds field names to reflect recent changes

L78-python-rich-server-context.md
gRFC: https://github.com/stpierre/proposal/blob/l78-python-rich-server-context/L78-python-rich-server-context.md
=> L78: Python: Expose rich server context

A36-xds-for-servers.md
I've updated the A36-xds-for-servers.md doc with API details for Core and C++. Please let me know if a new gRFC would be preferred.
=> Add xds-enabled server creation details for Core and C++

L79-cpp-byte-buffer-slice-methods.md
Discussion: https://groups.google.com/g/grpc-io/c/OsAYW1mDJ9w
=> L79: C++ API changes on ByteBuffer and Slice

L80-cpp-async-response-reader-destruction.md
See discussion on https://github.com/grpc/grpc/pull/26389.
@soheilhy
=> L80: change to only a minor version bump.

A41-xds-rbac.md
These were forgotten before merging #237.
=> A41: Update Status and Last-Modified

A36-xds-for-servers.md
A36 Core/C++ API update: Use a struct for serving status to allow more fields to be added in the future
=> A36 Core/C++ API update : Use a struct for serving status

L94-core-eliminate-slice-interning.md, L94-core-remove-slice-interning-apis.md
Implemented in https://github.com/grpc/grpc/pull/28363.
=> L94: C-core: Eliminate slice interning

A43-grpc-authorization-api.md, A43-sdk-authorization.md
This proposal discusses how gRPC authorization solution will be made available to OSS gRPC users. It covers details on gRPC SDK authorization policy (user facing policy language) and shows how to enable authorization controls in C++, Go and Java.
=> A43: gRPC Authorization API

A6-client-retries.md
See https://docs.microsoft.com/en-us/aspnet/core/grpc/retries?view=aspnetcore-6.0
=> A6 update: .NET supports client retries

A50-xds-outlier-detection.md
Sorry, made a mistake pushing commit responding to comments in #300. This PR actually responds to Menghan's and Eric's comments.
=> A50 update: Actually responded to comments

A52-xds-custom-lb-policies.md
=> A52 update: Mention gating by env flag

A50-xds-outlier-detection.md
=> A50 update: Add details about environment variable protection

A50-xds-outlier-detection.md
This PR changes the Update Addresses algorithm to get rid of the inconsistency of the fact that the Addresses tracked and counted for Outlier Detection are determined by the resolver Address list passed in. UpdateAddresses() call for a specific SubConn shouldn't mutate the map state and determine what Addresses are tracked for Outlier Detection. Also, added to eject a SubConn going from multiple -> single address where the new address is ejected.
=> Changed Update Addresses algorithm

A52-xds-custom-lb-policies.md
=> A52 update: Include mention of least_request LB support

L73-java-binderchannel.md
We've decided against open-sourcing OnDevice*Builder, and have deprecated it in favour using InProcessServer and BinderServer separately.
Since we're no longer planning to contribute this, remove it from the gRFC.
=> L73-java-binderchannel - Remove OnDevice*Builder.

A57-xds-client-failure-mode-behavior.md
=> A57: XdsClient Failure Mode Behavior

L70-node-proto-loader-type-generator.md
Update proposal corresponds to https://github.com/grpc/grpc-node/pull/2281
=> L70 update: Type branding for proto-loader-gen-types

A18-tcp-user-timeout.md
=> Update A18: Java was implemented in 2019

A66-otel-stats.md
It seems that we added the target attribute filter before the requirements for it arose. It is currently creating complications for us. Removing the requirement from the gRFC till we actually need it.
=> A66 update: Remove target attribute filter for now

L112-node-server-interceptors.md
I need this for the xDS server to do virtual host selection
=> L112 update: Add getHost method to ServerInterceptingCall

A64-lrs-custom-metrics.md
Java and Go implementation has been done.
=> A64 update: Update implementation status

A79-non-per-call-metrics-architecture.md
This updates A79 with the CallbackGauge APIs in C++.
=> A79 update: Update C++ API with CallbackGauge APIs

A79-non-per-call-metrics-architecture.md
This PR adds Go API's to A79, and adds me as an author.
=> A79 update: Add Go APIs

A83-xds-gcp-authn-filter.md
=> A83 update: add details about filter state retention/sharing mechanism

A83-xds-gcp-authn-filter.md
Updating this to reflect the actual C-core implementation on the server side, after discussion spawned from #491.
=> A83 update: document C-core filter state retention on server side
